# This is a basic workflow to help you get started with Actions

name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: tuxedo-big-file-uploads # optional, remove if GitHub repo name matches SVN slug, including capitalization

    - name: Create Github release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        body: ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifactContentType: application/zip
